### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by pand0rausa** [BloodHoundAD/SharpHound2#1]
When I open a powershell session (enter-pssession) to a remote system and execute SharpHound on the remote system it hangs for a few minutes before returning the below exception. Otherwise, if I run it locally on my machine it works fine. Same network.

Initializing BloodHound at 11:08 AM on 9/22/2017
Starting enumeration for xxxxxxxx
.\SharpHound.exe :
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception:
System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.
   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at Sharphound2.Utils.GetDomainSid(String domainName)
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)

**Comment by rvazarkar** [comment]
Thanks for the report we'll try and have a fix for this soon! Someone else
reported this internally already
