### ISSUE TITLE
Sharphound -> Unhandled Exception: The specified domain does not exist or cannot be contacted.

### ISSUE THREAD

**Issue by timm--** [BloodHoundAD/SharpHound2#17]
Not sure - maybe a linked domain (with trust) doesn't exist or respond? Sharphound was executed with defaults (i.e.: no args).

-------
Status: 21310 objects enumerated (+230 20.23742/s --- Using 70 MB RAM )
Status: 21612 objects enumerated (+302 19.95568/s --- Using 68 MB RAM )
Status: 22024 objects enumerated (+412 19.78796/s --- Using 69 MB RAM )
Status: 22043 objects enumerated (+19 19.28521/s --- Using 55 MB RAM )
Status: 22043 objects enumerated (+0 18.79199/s --- Using 55 MB RAM )
Status: 22043 objects enumerated (+0 18.32336/s --- Using 49 MB RAM )
Status: 22043 objects enumerated (+0 17.87753/s --- Using 49 MB RAM )
Status: 22043 objects enumerated (+0 17.45289/s --- Using 49 MB RAM )
Status: 22044 objects enumerated (+1 17.04872/s --- Using 48 MB RAM )
Status: 22044 objects enumerated (+0 16.66213/s --- Using 45 MB RAM )

Unhandled Exception: System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Sharphound2.Utils.GetDomain(String domainName)
   at Sharphound2.Utils.ResolveHost(String hostName)
   at Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)
---> (Inner Exception #0) System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Sharphound2.Utils.GetDomain(String domainName)
   at Sharphound2.Utils.ResolveHost(String hostName)
   at Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Sharphound2.Utils.GetDomain(String domainName)
   at Sharphound2.Utils.ResolveHost(String hostName)
   at Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by timm--** [comment]
Tested, and it happens during Session enumeration specifically

**Comment by paalbra** [comment]
As far as I can tell the code flows through here:

1. https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Enumeration/EnumerationRunner.cs#L117
2. https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Enumeration/SessionHelpers.cs#L141
3. https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Utils.cs#L85
4. https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Utils.cs#L613

I find it hard to say what's going on here without more debug info/knowledge of what some of the input variables are.

Getting to know what `domainName` is here...:
https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Utils.cs#L612

And `hostName` here...:
https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Utils.cs#L81

... seems like a reasonable place to start debuging.

@timm-- Have you ever compiled this project yourself or are you using the pre-compiled exe? Will you be able add some debug output yourself and recompile?

PS. I'm just getting acquainted with this project/code and not a maintainer. I'm just trying to help with some input on this issue :)

**Comment by rvazarkar** [comment]
Should be fixed in https://github.com/BloodHoundAD/SharpHound/commit/9ab151ad734b67483b2d03c9cf1f9271eeb7ddb7

**Comment by deveshm** [comment]
Changing the following lines worked for me:
https://github.com/BloodHoundAD/SharpHound/blob/0a3d044b6c768917ff851a80f7bb0ce244da0427/Sharphound2/Utils.cs#L811
https://github.com/BloodHoundAD/SharpHound/blob/0a3d044b6c768917ff851a80f7bb0ce244da0427/Sharphound2/Utils.cs#L838
https://github.com/BloodHoundAD/SharpHound/blob/0a3d044b6c768917ff851a80f7bb0ce244da0427/Sharphound2/Utils.cs#L840

I changed `DirectoryContextType.Domain` to `DirectoryContextType.DirectoryServer`
