### ISSUE TITLE
Unhandled Exception when using the CollectionMethods Group,ObjectProps

### ISSUE THREAD

**Issue by jopels** [BloodHoundAD/SharpHound2#49]
Used Version: BloodHound 2.0.5
OS: Win10

When calling SharpHound with the following command I get and unhandled exception:

`& .\SharpHound.exe --CollectionMethod Group,ObjectProps `

```
SharpHound.exe : 
Au caractère C:\Users\tgien\Desktop\\BloodHound\BloodHound-win32-x64\resources\app\Ingestors\StartSharpHoundDebug.ps1:1 : 1
+ & .\SharpHound.exe --CollectionMethod Group,ObjectProps
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Unhandled Exception:
 
System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Sharphound2.Enumeration.ObjectPropertyHelpers.GetProps(SearchResultEntry entry, ResolvedEntry resolved, Domain& obj)
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass19_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Sharphound2.Enumeration.ObjectPropertyHelpers.GetProps(SearchResultEntry entry, ResolvedEntry resolved, Domain& obj)
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass19_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/SharpHound/commit/2f9edd24e822e6e50315a2bf14f2166c97f8bc2e
