### ISSUE TITLE
SharpHound Unhandled Exception

### ISSUE THREAD

**Issue by mubix** [BloodHoundAD/SharpHound2#7]
Running latest build, and with default + verbose
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Sharphound2.DnsManager.HostExistsDns(String host, String& name)
   at Sharphound2.Extensions.ResolveAdEntry(SearchResultEntry result)
   at Sharphound2.Enumeration.LocalAdminHelpers.<GetGpoAdmins>d__13.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.StartStealthEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)
```

**Comment by rvazarkar** [comment]
Should be fixed in https://github.com/BloodHoundAD/SharpHound/commit/1b689d7354407105a7e96aed8b551d6886879731

Good catch!
