### ISSUE TITLE
Unhandled Exception: AggregateException_ctor_DefaultMessage 

### ISSUE THREAD

**Issue by maketsi** [BloodHoundAD/SharpHound2#72]
Some part of the Default collection methods crash for a rather large domain. I started the collection on a non-domain workstation by using runas. Collecting just the Groups works.
Running sharphound version 2.1.0.

.\SharpHound.exe --Domain "my.domain" --Verbose --StatusInterval 10000

...
Status: 175701 objects enumerated (+1703 81.41844/s --- Using 229 MB RAM )
Status: 181865 objects enumerated (+6164 83.88607/s --- Using 238 MB RAM )
Status: 186061 objects enumerated (+4195 85.42746/s --- Using 275 MB RAM )
Waiting for enumeration threads to finish
Status: 187378 objects enumerated (+1317 85.63894/s --- Using 224 MB RAM )
Status: 187378 objects enumerated (+0 85.24932/s --- Using 224 MB RAM )
Status: 187378 objects enumerated (+0 84.86323/s --- Using 223 MB RAM )
Status: 187378 objects enumerated (+0 84.48061/s --- Using 223 MB RAM )
Status: 187378 objects enumerated (+0 84.10143/s --- Using 223 MB RAM )
Status: 187378 objects enumerated (+0 83.72565/s --- Using 223 MB RAM )
Status: 187378 objects enumerated (+0 83.3532/s --- Using 223 MB RAM )

Unhandled Exception: System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sharphound2.Enumeration.TrustHelpers.DoTrustEnumeration(ResolvedEntry resolved, Domain& obj) in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\TrustHelpers.cs:line 97
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass22_0.<StartRunner>b__0() in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:line 1183
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration() in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:line 657
   at Sharphound2.Sharphound.Main(String[] args) in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Sharphound.cs:line 701
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Sharphound2.Enumeration.TrustHelpers.DoTrustEnumeration(ResolvedEntry resolved, Domain& obj) in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\TrustHelpers.cs:line 97
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass22_0.<StartRunner>b__0() in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:line 1183
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by MrMagiic** [comment]
I am getting the same error with the powershell version. It gets to a certain point, throws the error("Unhandled exception: AggregateException_ctor_DefaultMessage") and "continues" with the same amount of objects.
In addition the files are unrecognized by bloodhound as the files are not written probably (not closing the json correct etc.)
This was also on a relatively big domain.

**Comment by hkelley** [comment]
Mine crashes during a multi-day session loop (in GetNetSessions, based on the trace below):

`
Status: 3939 objects enumerated (+189 6.565/s --- Using 99 MB RAM )
Status: 4106 objects enumerated (+167 6.51746/s --- Using 99 MB RAM )
Status: 4234 objects enumerated (+128 6.415152/s --- Using 99 MB RAM )
Status: 4437 objects enumerated (+203 6.421129/s --- Using 99 MB RAM )

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sharphound2.Enumeration.SessionHelpers.<GetNetSessions>d__8.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass22_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sharphound2.Enumeration.EnumerationRunner.StartSessionLoopEnumeration()
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)
`

**Comment by rvazarkar** [comment]
This should be fixed in more recent builds. If you're still having the issue, please open a new issue here
